version: "3"
services:
  backend:
    image: node:21
    container_name: backend
    working_dir: /app
    command: npm run server
    ports:
      - "3001:3001"
    volumes:
      - "./backend/:/app"

  
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"





