version: "3"
services:
  backend:
    image: node:21
    container_name: backend
    working_dir: /app
    command: npm run server
    ports:
      - "3001:3001"
    volumes:
      - "./backend/:/app"

  frontend:
      image: node:21
      container_name: frontend
      working_dir: /src
      command: npm start
      ports:
        - "3000:3000"
      volumes:
        - "./frontend/:/src"
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"





